//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalOgloszeniowy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisment
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int CategoryId { get; set; }
        public int CityId { get; set; }
        public Nullable<int> Visits { get; set; }
        public bool IsPremium { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Pub_Time { get; set; }
        public System.DateTime Exp_Time { get; set; }
        public Nullable<int> Adv_Desc_Id { get; set; }
    
        public virtual AdvDesc AdvDesc { get; set; }
        public virtual City City { get; set; }
        public virtual Category Category { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
