//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalOgloszeniowy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryAttribute
    {
        public int Id { get; set; }
        public int CatId { get; set; }
        public int AttrId { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Category Category { get; set; }
    }
}
