//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalOgloszeniowy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keywords
    {
        public int Id { get; set; }
        public int AdvId { get; set; }
        public string Keyword { get; set; }
    
        public virtual Advertisment Advertisment { get; set; }
    }
}
